language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 6.10.2
before_install:
  - npm install -g npm
script:
  - npm run link
  - npm run build
  - cd examples/simple
  - npm link roc-plugin-test-jest
  - npm install
  - npm run test
